version: '3.7' # specify docker-compose version

# Define the services/containers to be run
services:
  angular9: # name of the first service
    hostname: localhost
    build: angular9 # specify the directory of the Dockerfile
    ports:
      - "4200:4200" # specify port forewarding
    image: mean_bank_angular9_1
  
  server: #name of the second service
    build: server # specify the directory of the Dockerfile
    ports:
      - "3000:3000" #specify ports forewarding
    image: mean_bank_server_1
    links:
      - mongo

  mongo: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27017:27017" # specify port forewarding